/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/study-groups": {
    /**
     * Get all study groups
     * @description Retrieve a list of all available study groups
     */
    get: {
      responses: {
        /** @description A list of study groups */
        200: {
          content: {
            "application/json": {
              success?: boolean;
              data?: {
                  /** Format: uuid */
                  id?: string;
                  name?: string;
                }[];
            };
          };
        };
      };
    };
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: never;
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export type operations = Record<string, never>;
